# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9689d92ebfee34ae574bb11313651290ab569c2a430a1678407c4b326e365bbe208d589a9124b18561a8a8311c0ccc246227cbc15afa868552d38a73ac03ea0b

test:
  secret_key_base: 680a7257734744bbc002df9609049198e87fb20a1358b9b5e0f46cdeb2b575f1a91d3c6b94210aa474e3b31272998b5bc64e53d750cbefc2604f1639ed9d22d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
